In [ ]:
import os
project_name = "reco-tut-vrr"; branch = "main"; account = "sparsh-ai"
project_path = os.path.join('/content', project_name)

In [ ]:
if not os.path.exists(project_path):
    !cp /content/drive/MyDrive/mykeys.py /content
    import mykeys
    !rm /content/mykeys.py
    path = "/content/" + project_name; 
    !mkdir "{path}"
    %cd "{path}"
    import sys; sys.path.append(path)
    !git config --global user.email "recotut@recohut.com"
    !git config --global user.name  "reco-tut"
    !git init
    !git remote add origin https://"{mykeys.git_token}":x-oauth-basic@github.com/"{account}"/"{project_name}".git
    !git pull origin "{branch}"
    !git checkout main
else:
    %cd "{project_path}"

/content/reco-tut-vrr
Initialized empty Git repository in /content/reco-tut-vrr/.git/
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 22 (delta 3), reused 20 (delta 2), pack-reused 0
Unpacking objects: 100% (22/22), done.
From https://github.com/sparsh-ai/reco-tut-vrr
 * branch            main       -> FETCH_HEAD
 * [new branch]      main       -> origin/main
Branch 'main' set up to track remote branch 'main' from 'origin'.
Switched to a new branch 'main'


In [ ]:
!git status

In [ ]:
!git add . && git commit -m 'commit' && git push origin "{branch}"

[main 58b1e77] commit
 2 files changed, 850 deletions(-)
 delete mode 100644 data/bronze/data.csv
 create mode 100644 data/silver/reviews.parquet.gzip
Counting objects: 6, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (6/6), 33.96 KiB | 16.98 MiB/s, done.
Total 6 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/sparsh-ai/reco-tut-vrr.git
   bb5b475..58b1e77  main -> main


---

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import nltk
import re
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics.pairwise import linear_kernel
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras import models
from keras.layers.embeddings import Embedding

import warnings
warnings.filterwarnings('ignore')

In [ ]:
nltk.download('wordnet')
nltk.download('stopwords')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
df = pd.read_parquet('./data/silver/reviews.parquet.gzip')
df.head()

Title  ...                                            Reviews
0                            Vacation/Cottage Rental  ...    This rental felt more like a well-appointed ...
1    Mistiso's Place Vacation Rentals- Purcell Suite  ...    I can't say enough about this beautiful and ...
2  Toronto 4 Bedroom House Spacious Clean Beautif...  ...    back yard! Would recommend the rental for a ...
3                                   Our Sweet Escape  ...    enjoyable. I have never stayed in a vacation...
4    Walk to ocean from Lyons Cottage Rentals in PEI  ...    quiet morning as we woke up - perfect vacati...

[5 rows x 6 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 571 entries, 0 to 570
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Title          571 non-null    object 
 1   Rating         571 non-null    int64  
 2   Review_counts  571 non-null    float64
 3   City           571 non-null    object 
 4   Province       571 non-null    object 
 5   Reviews        571 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 26.9+ KB


In [ ]:
#filter punctuations, stemming and stopwords
corpus = []
for i in range(len(df)):
    review = re.sub('[^a-zA-Z0-9]', ' ', df['Reviews'][i])
    review = review.lower()
    tokenizer = nltk.tokenize.WhitespaceTokenizer()
    stemmer = nltk.PorterStemmer()
    lemmatizer = nltk.WordNetLemmatizer()
    tokens_list = tokenizer.tokenize(review)
    tokens = []
    for token in tokens_list:
        tokens.append(lemmatizer.lemmatize(token))
        stop_words = stopwords.words("english")
    filtered_words = [w for w in tokens if w not in stop_words]
    review = ' '.join(filtered_words)
    corpus.append(review)

In [ ]:
print('length of coprus is {} and first item is "{}"'.format(len(corpus), corpus[0]))

length of coprus is 571 and first item is "rental felt like well appointed apartment vacation"


In [ ]:
#Bag of Words model to convert corpus into X
cv = CountVectorizer()
cv.fit(corpus)
key = list(cv.vocabulary_.keys())
key.sort()
X = pd.DataFrame(cv.transform(corpus).toarray(),columns = key)
y = df.Rating

In [ ]:
#TF_IDF model to convert corpus into X
tfidf = TfidfVectorizer()
X2 = pd.DataFrame(tfidf.fit_transform(corpus).toarray())

In [ ]:
Rating = df.Rating

In [ ]:
# We need to get unique words to determine the vocabulary size
reviews = df.Reviews
uniq_words=set()

for doc in reviews:
    for word in doc.split(" "):
        uniq_words.add(word)
vocab_size=len(uniq_words)

print ("Total Unique words:",vocab_size)

Total Unique words: 1856


## Review text to rating prediction

We need to convert each of the words in the reviews to one-hot vectors. Below is the code to get integer indexes of the words for one hot vector.

Note that we don't need to store all zeros as only the integer index for the word in a vector will have a value of 1.


In [ ]:
# Integer encode the documents
encoded_reviews = [one_hot(review, vocab_size) for review in reviews]
print(encoded_reviews[1])

[83, 255, 1673, 938, 1194, 691, 1432, 1516, 417, 219, 196]


In [ ]:
# We fix the maximum length to 100 words.
# pad documents to a max length of n words
max_length = 100
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[ 691  196  468 ...    0    0    0]
 [  83  255 1673 ...    0    0    0]
 [1706 1718 1213 ...    0    0    0]
 ...
 [ 219 1675 1281 ...    0    0    0]
 [ 113 1659  196 ...    0    0    0]
 [  86    0    0 ...    0    0    0]]


In [ ]:
# We have completed our pre-processing, it is now time to build the neural network based classifier. We start by splitting the reviews into training and test set.
X_train, X_test, y_train, y_test = train_test_split(padded_reviews,Rating,test_size=0.3, random_state=0)

Now we need to define the basics of model for neural network

In [ ]:
# define the model
model = Sequential()

# Define the embedding matrix dimensions. Each vector is of 8 dimensions and there will be total of vocab_size vectors
# The input length (window) is 100 words so the output from embedding layer will be a conactenated (flattened) vector of 
# 800 dimensions
model.add(Embedding(vocab_size, 16, input_length=max_length))
model.add(Flatten())
model.add(Dense(units=3, activation='relu'))
model.add(Dense(units=2, activation='relu'))
model.add(Dense(units=1, activation='relu'))

# compile the model with stochastic gradient descent and binary cross entropy
model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['acc'])

# summarize the model
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 100, 16)           29696     
_________________________________________________________________
flatten (Flatten)            (None, 1600)              0         
_________________________________________________________________
dense (Dense)                (None, 3)                 4803      
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 8         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 3         
Total params: 34,510
Trainable params: 34,510
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
# Fit the model... there are few docs, so I am trying with batch_size=1, you can delete it for default batch 
#size or change it to a bigger number
model.fit(X_train, y_train, epochs=10, batch_size=30, verbose=1)

Epoch 1/10
14/14 [==============================] - 14s 2ms/step - loss: -10.6064 - acc: 0.0023
Epoch 2/10
14/14 [==============================] - 0s 2ms/step - loss: -67.6475 - acc: 0.0023
Epoch 3/10
14/14 [==============================] - 0s 2ms/step - loss: -67.2081 - acc: 0.0033
Epoch 4/10
14/14 [==============================] - 0s 2ms/step - loss: -69.0307 - acc: 0.0014
Epoch 5/10
14/14 [==============================] - 0s 2ms/step - loss: -67.9948 - acc: 0.0033
Epoch 6/10
14/14 [==============================] - 0s 2ms/step - loss: -69.1731 - acc: 0.0016
Epoch 7/10
14/14 [==============================] - 0s 2ms/step - loss: -67.9859 - acc: 5.0511e-04
Epoch 8/10
14/14 [==============================] - 0s 2ms/step - loss: -68.1371 - acc: 0.0023
Epoch 9/10
14/14 [==============================] - 0s 2ms/step - loss: -67.6506 - acc: 0.0033
Epoch 10/10
14/14 [==============================] - 0s 2ms/step - loss: -68.5652 - acc: 0.0020


Now, we shall evaluate our model against the test set that we kep separate earlier.

In [ ]:
# evaluate the model
loss, accuracy = model.evaluate(X_test, y_test, verbose=1)
print('Accuracy: %f' % (accuracy*100))

6/6 [==============================] - 1s 3ms/step - loss: -69.2422 - acc: 0.0058
Accuracy: 0.581395


Precision and Recall

In [ ]:
predictions = model.predict(X_test, batch_size=100, verbose=1)
predictions_bool = np.argmax(predictions, axis=1)

print(classification_report(y_test, predictions_bool))

2/2 [==============================] - 0s 4ms/step
              precision    recall  f1-score   support

           0       0.01      1.00      0.01         1
           1       0.00      0.00      0.00         1
           3       0.00      0.00      0.00         3
           4       0.00      0.00      0.00         9
           5       0.00      0.00      0.00        41
           6       0.00      0.00      0.00       117

    accuracy                           0.01       172
   macro avg       0.00      0.17      0.00       172
weighted avg       0.00      0.01      0.00       172

